apiVersion: apps/v1
kind: Deployment
metadata:
  name: candy-store
  labels:
    app: candy-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: candy-store
  template:
    metadata:
      labels:
        app: candy-store
    spec:
      containers:
        - name: candy-store-container
          image: nginx:latest
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: candy-store-service
spec:
  selector:
    app: candy-store
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
