apiVersion: apps/v1
kind: Deployment
metadata:
  name: candy-store
  labels:
    app: candy-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: candy-store
  template:
    metadata:
      labels:
        app: candy-store
    spec:
      containers:
        - name: candy-store
          image: francisreddy/candy-store:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: candy-store-service
spec:
  type: NodePort
  selector:
    app: candy-store
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
